---
title: "Руслан Хазарзар: Cын человеческий"
timezone: France/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: 
baseurlcomm: https://ru.khazarzar.bak.re
maininstitutesite: 
author: '2000–2013, Руслан Хазарзар <sup>[1](http://khazarzar.livejournal.com "Живой журнал"), [2](http://hazarzar.livejournal.com "Текущее")</sup>'
simple_search: http://google.com/search
markdown: kramdown
permalink: "/articles/:short_year/:title"
excerpt_separator: "<!--more-->"
exclude:
- Gemfile
- Gemfile.lock
- Rakefile
- UploadToGithub.Rakefile
- README.md
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
